sudo: required
services:
 - docker

before_install:
 - docker build -t vidyaaprabha/react-test -f ./client/Dockerfile.dev .

script:
   - docker run -e CI=true vidyaaprabha/react-test npm test -- --coverage
after_success:
   - docker build -t vidyaaprabha/multi_client ./client
   - docker build -t vidyaaprabha/multi_worker ./worker
   - docker build -t vidyaaprabha/multi_server ./server
   - docker build -t vidyaaprabha/multi_nginx ./nginx

   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   
   - docker push vidyaaprabha/multi_client
   - docker push vidyaaprabha/multi_worker
   - docker push vidyaaprabha/multi_nginx
   - docker push vidyaaprabha/multi_server
